services:
  backend:
    build:
      context: ./backend
    command: uvicorn src.main:create_app --reload --host 0.0.0.0 --factory
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    restart: on-failure
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017

volumes:
  mongodb_data:
    driver: local