services:
  backend:
    build:
      context: ./backend
    command: uvicorn src.main:create_app --reload --host 0.0.0.0 --factory
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    restart: on-failure
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend:delegated
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_BACKEND_URL=http://127.0.0.1:8000
    restart: always
volumes:
  mongodb_data:
    driver: local